# Generated by Django 3.2 on 2021-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemCategory',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='itemType',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
