# Generated by Django 3.2 on 2021-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210515_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
