# Generated by Django 3.2 on 2021-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizeTo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
