# Generated by Django 3.2 on 2021-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_sizeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizeLetter',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
