# Generated by Django 3.2 on 2021-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_sizeletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizeLetter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
