# Generated by Django 3.2 on 2021-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_sizeletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
