# Generated by Django 3.2 on 2021-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizeLetter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeTo',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
