# Generated by Django 3.2 on 2021-06-01 15:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.CharField(default=api.models.randomProductID, max_length=20),
        ),
    ]
