# Generated by Django 3.2 on 2021-06-01 15:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_product_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.CharField(default=api.models.randomProductID, max_length=20),
        ),
    ]
