# Generated by Django 3.2 on 2021-06-02 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
