# Generated by Django 3.2 on 2021-06-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
