# Generated by Django 3.2 on 2021-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='images',
        ),
        migrations.AddField(
            model_name='featured',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
