# Generated by Django 3.2 on 2021-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
