# Generated by Django 3.2 on 2021-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_coupons_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
