# Generated by Django 3.2 on 2021-06-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_temporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='total',
            field=models.FloatField(),
        ),
    ]
