# Generated by Django 3.2 on 2021-06-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_temporder_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporder',
            old_name='cart',
            new_name='info',
        ),
    ]
