# Generated by Django 3.2 on 2021-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_temporder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
