# Generated by Django 3.2 on 2021-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Complete', max_length=100),
            preserve_default=False,
        ),
    ]
